version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20  # Specify the Node.js version

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      # Use 'aws ecr get-login-password' to get the authentication token for Docker
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 904463569708.dkr.ecr.us-east-1.amazonaws.com
      - echo Pre-build completed...

  build:
    commands:
    
      - echo Building the Docker image...
      # Build the Docker image using the Dockerfile in the current directory ('.')
      - docker build -t keywe-pro-image .
      - echo Tagging the Docker image...
      # Tag the Docker image with the repository URI
      # - docker tag keywe-web:latest 904463569708.dkr.ecr.us-east-1.amazonaws.com/keywe-web:latest
      - docker tag keywe-pro-image:latest 904463569708.dkr.ecr.us-east-1.amazonaws.com/keywe-pro-repo:latest
      - echo Build completed...

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      # Push the Docker image to Amazon ECR
      # - docker push 904463569708.dkr.ecr.us-east-1.amazonaws.com/keywe-web:latest
      - docker push 904463569708.dkr.ecr.us-east-1.amazonaws.com/keywe-pro-repo:latest
      - echo Writing image definitions file...
      # Write the image definition JSON file
      - printf '[{"name":"%s","imageUri":"%s"}]' keywe-pro-image 904463569708.dkr.ecr.us-east-1.amazonaws.com/keywe-pro-image:latest > imagedefinitions.json
      - echo Post-build completed...

artifacts:
  files:
    - imagedefinitions.json
